### ISSUE TITLE
KeyError: "The name 'highres_input:0' refers to a Tensor which does not exist.

### ISSUE THREAD

**Issue by butterl** [DaFun/Image-Enhancement#2]
Hi,
Thanks for sharing this great demo， I tried use the web app， but it seems stuck from both mobile and my laptop after selecting picture.

I tried run the test pb_graph.py it seems find no 'highres_input:0' tensor, do you get any advice that I could eval the model? thanks

```
input_path=./input.png
Traceback (most recent call last):
  File "test_pb_graph.py", line 82, in <module>
    main(args)
  File "test_pb_graph.py", line 59, in main
    fullres = graph.get_tensor_by_name('highres_input:0')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3635, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3459, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3501, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'highres_input:0' refers to a Tensor which does not exist. The operation, 'highres_input', does not exist in the graph."
```

**Comment by butterl** [comment]
@DaFun  added some print，  not sure why these could not be found

```
for op in tf.get_default_graph().get_operations():
    print("op name: ", op.name)

op name:  import/lowres_input
op name:  import/fullres_input
op name:  import/output_img
```
